name: DiabloSmpPlugin
version: 1.0.0
main: com.diablosmp.plugin.DiabloPlugin
api-version: 1.21
description: Boss Pack for Diablo SMP
commands:
  diablo:
    description: Admin commands.
    permission: diablo.admin
  trust:
    description: Trust players for item trade.
